<?php

/**
 * @file
 * Module file for views_infinite_scroll.
 */

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // The important parts we needed lifted wholesale from
  // template_preprocess_views_mini_pager().
  global $pager_page_array, $pager_total;
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  if ($pager_page_array[$element] < ($pager_total[$element] - 1)) {
    $options = array(
      'query' => pager_query_add_page($parameters, $element, $pager_page_array[$element] + 1),
    );
    $vars['items']['next']['href'] = \Drupal::url('<current>', [], $options);
  }
  $vars['#cache']['contexts'][] = 'url.query_args';
}
